//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ag_ClosingStock
    {
        public long ID { get; set; }
        public long Pcode { get; set; }
        public string PName { get; set; }
        public decimal Pprice { get; set; }
        public decimal OpenStock { get; set; }
        public decimal ChangeInStock { get; set; }
        public decimal ClosingStock { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime Transdate { get; set; }
        public string Auditid { get; set; }
        public decimal opstock { get; set; }
        public System.DateTime opdate { get; set; }
        public Nullable<decimal> sales { get; set; }
        public Nullable<decimal> Purchase { get; set; }
    }
}
