//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ag_lpo
    {
        public long ID { get; set; }
        public string pono { get; set; }
        public string vendor { get; set; }
        public Nullable<System.DateTime> lpodate { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public string lposerialno { get; set; }
        public string remarks { get; set; }
        public string itemno { get; set; }
        public string itemname { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
    }
}
