//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ag_Moringaintake
    {
        public long id { get; set; }
        public Nullable<int> Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> System { get; set; }
        public Nullable<decimal> Actual { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> auditedatetime { get; set; }
    }
}
