//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ag_paging
    {
        public long id { get; set; }
        public string pcode { get; set; }
        public Nullable<System.DateTime> ldate { get; set; }
        public Nullable<System.DateTime> ltdate { get; set; }
        public Nullable<long> dy { get; set; }
        public Nullable<System.DateTime> auditdate { get; set; }
        public string audit { get; set; }
        public string grade { get; set; }
    }
}
