//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ag_ReceiptsProcess
    {
        public long ID { get; set; }
        public string SNo { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public double Pro1 { get; set; }
        public double Pro2 { get; set; }
        public double Pro3 { get; set; }
        public double Pro4 { get; set; }
        public double Pro5 { get; set; }
        public double Pro6 { get; set; }
        public double Pro7 { get; set; }
        public double Pro8 { get; set; }
        public double Pro9 { get; set; }
        public double sPro1 { get; set; }
        public double sPro2 { get; set; }
        public double sPro3 { get; set; }
        public double sPro4 { get; set; }
        public double sPro5 { get; set; }
        public double sPro6 { get; set; }
        public double sPro7 { get; set; }
        public double sPro8 { get; set; }
        public double sPro9 { get; set; }
        public string Branch { get; set; }
        public double bPro1 { get; set; }
        public double bPro2 { get; set; }
        public double bPro3 { get; set; }
        public double bPro4 { get; set; }
        public double bPro5 { get; set; }
        public double bPro6 { get; set; }
        public double bPro7 { get; set; }
        public double bPro8 { get; set; }
        public double bPro9 { get; set; }
    }
}
