//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ag_stockbalance1
    {
        public int trackid { get; set; }
        public string p_code { get; set; }
        public string productname { get; set; }
        public Nullable<decimal> openningstock { get; set; }
        public Nullable<decimal> changeinstock { get; set; }
        public Nullable<double> stockbalance { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public Nullable<int> companyid { get; set; }
        public string subclass { get; set; }
        public string R_NO { get; set; }
        public Nullable<long> S_NO { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> audit_date { get; set; }
    }
}
