//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ag_stockbalance
    {
        public int trackid { get; set; }
        public string p_code { get; set; }
        public string productname { get; set; }
        public Nullable<decimal> openningstock { get; set; }
        public Nullable<decimal> changeinstock { get; set; }
        public Nullable<double> stockbalance { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public Nullable<int> companyid { get; set; }
        public string subclass { get; set; }
        public string R_NO { get; set; }
        public string S_NO { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> audit_date { get; set; }
        public decimal Pprice { get; set; }
        public decimal Sprice { get; set; }
        public double RLevel { get; set; }
        public System.DateTime Auditdate { get; set; }
        public string Branch { get; set; }
        public Nullable<int> AI { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public Nullable<int> process1 { get; set; }
        public Nullable<int> process2 { get; set; }
        public string Remarks { get; set; }
    }
}
