//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        public int assetsid { get; set; }
        public string AssetsNo { get; set; }
        public string AssetserialNo { get; set; }
        public string AssetsName { get; set; }
        public string AssetType { get; set; }
        public Nullable<System.DateTime> datebought { get; set; }
        public Nullable<int> UnitNo { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<double> Depreciation { get; set; }
        public Nullable<decimal> Currentvalue { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<decimal> Accdepreciation { get; set; }
        public Nullable<decimal> revaluation { get; set; }
        public Nullable<decimal> NRVBF { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> disposaldate { get; set; }
        public Nullable<decimal> d_amount { get; set; }
        public string Accno { get; set; }
    }
}
