//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assets_register
    {
        public long asid { get; set; }
        public string assetcode { get; set; }
        public string assetname { get; set; }
        public double deprate { get; set; }
        public string accno { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal CurrentValue { get; set; }
        public System.DateTime Pdate { get; set; }
        public string SerialNo { get; set; }
        public string ContraAccno { get; set; }
    }
}
