//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITTRANS1
    {
        public long Transid { get; set; }
        public string Transtable { get; set; }
        public string Transdescription { get; set; }
        public System.DateTime Transdate { get; set; }
        public decimal Amount { get; set; }
        public string Auditid { get; set; }
        public System.DateTime Audittime { get; set; }
    }
}
