//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2CDisbursementResponse
    {
        public int id { get; set; }
        public Nullable<int> ResultCode { get; set; }
        public Nullable<int> ResultType { get; set; }
        public string ResultDesc { get; set; }
        public string OriginatorConversationID { get; set; }
        public string ConversationID { get; set; }
        public string TransactionId { get; set; }
        public string TransacionReceipt { get; set; }
        public string Amount { get; set; }
        public string B2CUtilityAccountAvailableFunds { get; set; }
        public string TransactionCompletedDateTime { get; set; }
        public string ReceiverPartyPublicName { get; set; }
        public Nullable<long> Run { get; set; }
        public string PhoneNo2 { get; set; }
        public Nullable<long> Run2 { get; set; }
    }
}
