//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2CPaymentDummy
    {
        public long id { get; set; }
        public string ReceiptNo { get; set; }
        public string SNo { get; set; }
        public string Names { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string Location { get; set; }
        public string OtherParyInfo { get; set; }
        public string TransactionStatus { get; set; }
        public string User1 { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public Nullable<long> Status1 { get; set; }
    }
}
