//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankRecon
    {
        public string AccNo { get; set; }
        public System.DateTime ReconDate { get; set; }
        public System.DateTime OpeningBalDate { get; set; }
        public decimal OpeningBal { get; set; }
        public decimal Receipts { get; set; }
        public decimal Payments { get; set; }
        public decimal Unpresented { get; set; }
        public decimal UnCredited { get; set; }
        public decimal DirectCredits { get; set; }
        public decimal DirectDebits { get; set; }
        public decimal StatementBal { get; set; }
        public decimal CashBookBal { get; set; }
        public long ReconId { get; set; }
    }
}
