//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class barcodedsale
    {
        public int serialid { get; set; }
        public string serialcode { get; set; }
        public Nullable<int> units { get; set; }
        public string stockname { get; set; }
        public Nullable<decimal> sellingprice { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public string paymenttype { get; set; }
        public string chequeno { get; set; }
        public string batchno { get; set; }
    }
}
