//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHBOOK
    {
        public long CashID { get; set; }
        public string TransID { get; set; }
        public string MemberNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransDescript { get; set; }
        public string ReceiptNo { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> Posted { get; set; }
        public Nullable<int> IsMember { get; set; }
        public string AccNo { get; set; }
        public string AccNoCr { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
    }
}
