//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashbookTransaction
    {
        public long CashId { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public string Vno { get; set; }
        public string Transtype { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Chequeno { get; set; }
        public string Accno { get; set; }
        public string Transdescription { get; set; }
        public Nullable<int> IdNo { get; set; }
        public Nullable<int> Reconciled { get; set; }
        public string Pd { get; set; }
        public string Transby { get; set; }
    }
}
