//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CInvoice()
        {
            this.CInvoiceDetails = new HashSet<CInvoiceDetail>();
            this.CInvoiceJournals = new HashSet<CInvoiceJournal>();
        }
    
        public System.Guid Id { get; set; }
        public string Customer { get; set; }
        public string Ref { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Journal { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Arrears { get; set; }
        public string Status { get; set; }
        public string PaymentReference { get; set; }
        public string SalesPerson { get; set; }
        public string RecipientBank { get; set; }
        public string IncoTerm { get; set; }
        public string FiscalPosition { get; set; }
        public string Personnel { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SaccoCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CInvoiceDetail> CInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CInvoiceJournal> CInvoiceJournals { get; set; }
    }
}
