//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinic_stkpayresults
    {
        public long Id { get; set; }
        public string MerchantRequestID { get; set; }
        public string CheckoutRequestID { get; set; }
        public string MemberNo { get; set; }
        public string TopicId { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<int> ResultCode { get; set; }
        public string ResultDesc { get; set; }
        public string Amount { get; set; }
        public string Balance { get; set; }
        public string MpesaReceiptNumber { get; set; }
        public string TransactionDate { get; set; }
        public string PhoneNumber { get; set; }
    }
}
