//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUB
    {
        public long Cuid { get; set; }
        public string MemberNo { get; set; }
        public string AccNo { get; set; }
        public string IDNo { get; set; }
        public string Payno { get; set; }
        public string AccountName { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Transdescription { get; set; }
        public Nullable<decimal> AvailableBalance { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public string VNO { get; set; }
        public string ChequeNo { get; set; }
        public string Transtype { get; set; }
        public string picture { get; set; }
        public string signature { get; set; }
        public string period { get; set; }
        public string AUDITID { get; set; }
        public Nullable<System.DateTime> Auditdate { get; set; }
        public string moduleid { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> CLOSED { get; set; }
        public Nullable<bool> FROZEN { get; set; }
        public string picture1 { get; set; }
        public Nullable<decimal> actualbalance { get; set; }
        public Nullable<decimal> unitmarked { get; set; }
        public Nullable<decimal> excess { get; set; }
        public Nullable<int> graceperiod { get; set; }
        public Nullable<System.DateTime> limitexpirydate { get; set; }
        public string branchcode { get; set; }
        public Nullable<bool> main { get; set; }
        public string controlacc { get; set; }
        public string branch_accno { get; set; }
        public string main_accno { get; set; }
        public string curr { get; set; }
        public Nullable<bool> status { get; set; }
        public string main_acc_header { get; set; }
        public Nullable<bool> NoticeG { get; set; }
        public Nullable<System.DateTime> DON { get; set; }
        public Nullable<System.DateTime> EDON { get; set; }
        public Nullable<decimal> Adbal { get; set; }
        public Nullable<decimal> hs { get; set; }
        public Nullable<decimal> ordshares { get; set; }
        public Nullable<decimal> loans { get; set; }
        public string tgno1 { get; set; }
        public string tgno2 { get; set; }
        public string tgno3 { get; set; }
        public string sex { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Nhif { get; set; }
        public string NOMI1 { get; set; }
        public string NOMI1ID { get; set; }
        public string NOMI2 { get; set; }
        public string NOMI2ID { get; set; }
        public string NOMI3 { get; set; }
        public string NOMI3ID { get; set; }
        public string SIG1 { get; set; }
        public string SIG1ID { get; set; }
        public string SIG2 { get; set; }
        public string SIG2ID { get; set; }
        public string SIG3 { get; set; }
        public string SIG3ID { get; set; }
        public string SIG4 { get; set; }
        public string SIG4ID { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> ledger { get; set; }
        public Nullable<bool> issubledger { get; set; }
        public Nullable<bool> hassubledgers { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
    }
}
