//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curr
    {
        public string CurrCode { get; set; }
        public string Description { get; set; }
        public string Symbol { get; set; }
        public Nullable<float> rateaganistsource { get; set; }
        public Nullable<short> Decimals { get; set; }
        public string Symbolposition { get; set; }
        public string ThousandSeparator { get; set; }
        public string DecimalSeparator { get; set; }
        public string NegativeDisplay { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
    }
}
