//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERBALANCEOLD
    {
        public long CustomerBalanceID { get; set; }
        public string CustomerNo { get; set; }
        public string IDNo { get; set; }
        public string PayrollNo { get; set; }
        public string AccName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AvailableBalance { get; set; }
        public string AccNo { get; set; }
        public string TransDescription { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string ChequeNo { get; set; }
        public string Period { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<bool> Locked { get; set; }
        public string TransType { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Vno { get; set; }
        public string Auditid { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string ModuleID { get; set; }
        public string AccD { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<decimal> ActualBalance { get; set; }
        public Nullable<bool> Cash { get; set; }
        public string Bcode { get; set; }
        public Nullable<bool> Rebuild { get; set; }
        public string TransNo { get; set; }
        public bool Reconciled { get; set; }
        public string Transfers { get; set; }
        public Nullable<int> dregard { get; set; }
    }
}
