//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_AssignmentVehicle
    {
        public long ID { get; set; }
        public string AccnoV { get; set; }
        public string Vehicle { get; set; }
        public string ExpenseAcc { get; set; }
        public string ExpeLedger { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UserID { get; set; }
    }
}
