//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Bonus2
    {
        public string Sno { get; set; }
        public Nullable<decimal> Mon1 { get; set; }
        public Nullable<decimal> Mon2 { get; set; }
        public Nullable<decimal> Mon3 { get; set; }
        public Nullable<decimal> Mon4 { get; set; }
        public Nullable<decimal> Mon5 { get; set; }
        public Nullable<decimal> Mon6 { get; set; }
        public Nullable<decimal> Mon7 { get; set; }
        public Nullable<decimal> Mon8 { get; set; }
        public Nullable<decimal> Mon9 { get; set; }
        public Nullable<decimal> Mon10 { get; set; }
        public Nullable<decimal> Mon11 { get; set; }
        public Nullable<decimal> Mon12 { get; set; }
        public System.DateTime Auditdatetime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
