//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Bonus
    {
        public string Sno { get; set; }
        public string Name { get; set; }
        public string Bank { get; set; }
        public string Bcode { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Pby { get; set; }
        public System.DateTime Auditdatetime { get; set; }
    }
}
