//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_CashShares
    {
        public long Id { get; set; }
        public System.DateTime Period { get; set; }
        public long SNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Ref { get; set; }
        public string AuditId { get; set; }
        public Nullable<System.DateTime> Auditdate { get; set; }
    }
}
