//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_CashPay
    {
        public long Id { get; set; }
        public string PayId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string CRacc { get; set; }
        public string DRacc { get; set; }
        public string Payee { get; set; }
        public string Descr { get; set; }
        public string VNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
