//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_DailySummary
    {
        public long Id { get; set; }
        public Nullable<long> SNo { get; set; }
        public Nullable<double> C1 { get; set; }
        public Nullable<double> C2 { get; set; }
        public Nullable<double> C3 { get; set; }
        public Nullable<double> C4 { get; set; }
        public Nullable<double> C5 { get; set; }
        public Nullable<double> C6 { get; set; }
        public Nullable<double> C7 { get; set; }
        public Nullable<double> C8 { get; set; }
        public Nullable<double> C9 { get; set; }
        public Nullable<double> C10 { get; set; }
        public Nullable<double> C11 { get; set; }
        public Nullable<double> C12 { get; set; }
        public Nullable<double> C13 { get; set; }
        public Nullable<double> C14 { get; set; }
        public Nullable<double> C15 { get; set; }
        public Nullable<double> C16 { get; set; }
        public Nullable<double> C17 { get; set; }
        public Nullable<double> C18 { get; set; }
        public Nullable<double> C19 { get; set; }
        public Nullable<double> C20 { get; set; }
        public Nullable<double> C21 { get; set; }
        public Nullable<double> C22 { get; set; }
        public Nullable<double> C23 { get; set; }
        public Nullable<double> C24 { get; set; }
        public Nullable<double> C25 { get; set; }
        public Nullable<double> C26 { get; set; }
        public Nullable<double> C27 { get; set; }
        public Nullable<double> C28 { get; set; }
        public Nullable<double> C29 { get; set; }
        public Nullable<double> C30 { get; set; }
        public Nullable<double> C31 { get; set; }
        public Nullable<System.DateTime> EndPeriod { get; set; }
        public Nullable<double> Total { get; set; }
        public string LOCATION { get; set; }
        public Nullable<long> local_id { get; set; }
        public Nullable<long> Run { get; set; }
    }
}
