//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Debtorsparchases2
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> kgs { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Paid_Amount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public string Vehicle { get; set; }
    }
}
