//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Debtors2
    {
        public long id { get; set; }
        public string Dcode { get; set; }
        public string DName { get; set; }
        public string CertNo { get; set; }
        public string Locations { get; set; }
        public Nullable<System.DateTime> TregDate { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
    }
}
