//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_dispatch
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public string descrip { get; set; }
        public double Intake { get; set; }
        public double dipping { get; set; }
        public double dispatch { get; set; }
        public string auditid { get; set; }
        public System.DateTime auditdate { get; set; }
    }
}
