//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_glposting
    {
        public long id { get; set; }
        public int mmonth { get; set; }
        public int yyear { get; set; }
        public Nullable<decimal> namount { get; set; }
        public bool posted { get; set; }
    }
}
