//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_LPO
    {
        public long Id { get; set; }
        public long PNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Serial { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> auditdatetieme { get; set; }
        public string auditid { get; set; }
        public string Remarks { get; set; }
        public string Vendor { get; set; }
    }
}
