//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_MilkControl
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> DispDate { get; set; }
        public Nullable<double> DispQnty { get; set; }
        public Nullable<double> DipQnty { get; set; }
        public Nullable<double> InQnty { get; set; }
        public Nullable<double> Variance { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string RefNo { get; set; }
        public string DebitAcc { get; set; }
        public string CreditAcc { get; set; }
        public string AuditId { get; set; }
        public Nullable<System.DateTime> Auditdatetime { get; set; }
        public string DCode { get; set; }
        public string vehicleno { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<long> Run { get; set; }
    }
}
