//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Milkintake1
    {
        public long ID { get; set; }
        public long SNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<decimal> QSupplied { get; set; }
        public Nullable<decimal> PPU { get; set; }
        public Nullable<decimal> PAmount { get; set; }
        public string TransTime { get; set; }
        public string AuditId { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
        public bool Paid { get; set; }
        public int LR { get; set; }
        public string remark { get; set; }
        public string comment { get; set; }
        public Nullable<bool> status1 { get; set; }
        public string LOCATION { get; set; }
        public Nullable<long> local_id { get; set; }
        public Nullable<long> Run { get; set; }
    }
}
