//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Outletbranch
    {
        public long id { get; set; }
        public string BCode1 { get; set; }
        public string BName1 { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
        public Nullable<int> Till { get; set; }
        public Nullable<int> PhoneNo { get; set; }
        public string Dr { get; set; }
        public string Cr { get; set; }
        public Nullable<long> Run { get; set; }
    }
}
