//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Outlet
    {
        public string p_code { get; set; }
        public string p_name { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public Nullable<double> Qin { get; set; }
        public Nullable<double> Qout { get; set; }
        public Nullable<double> o_bal { get; set; }
        public string user_id { get; set; }
        public Nullable<decimal> Wprice { get; set; }
        public Nullable<decimal> Rprice { get; set; }
        public string Branch { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<long> Run { get; set; }
    }
}
