//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_OutletSales
    {
        public long ID { get; set; }
        public string PCode { get; set; }
        public string PName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<double> Quant { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public string AuditId { get; set; }
        public string Description { get; set; }
        public string OutletName { get; set; }
        public string Mpesa { get; set; }
        public Nullable<long> Run { get; set; }
    }
}
