//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Payment
    {
        public long id { get; set; }
        public string RNo { get; set; }
        public string InvId { get; set; }
        public Nullable<long> PONo { get; set; }
        public Nullable<decimal> Amnt { get; set; }
        public string PayMode { get; set; }
        public string Vendor { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string GLAcc { get; set; }
        public string VNo { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
    }
}
