//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_PayrollCopy
    {
        public long id { get; set; }
        public string SNo { get; set; }
        public string Names { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string Location { get; set; }
        public Nullable<int> Yyear { get; set; }
        public Nullable<int> Mmonth { get; set; }
        public string Phoneno2 { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public Nullable<long> Status1 { get; set; }
        public Nullable<long> Status2 { get; set; }
        public Nullable<long> Status3 { get; set; }
        public Nullable<long> Run2 { get; set; }
    }
}
