//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Periods
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> EndPeriod { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string auditId { get; set; }
        public Nullable<System.DateTime> auditdateTime { get; set; }
    }
}
