//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_PreSets
    {
        public long Id { get; set; }
        public string SNo { get; set; }
        public string Deduction { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<bool> Stopped { get; set; }
        public Nullable<System.DateTime> Auditdatetime { get; set; }
        public string AuditId { get; set; }
        public Nullable<bool> Rated { get; set; }
        public Nullable<long> status { get; set; }
        public Nullable<long> status2 { get; set; }
        public Nullable<long> status3 { get; set; }
        public Nullable<long> status4 { get; set; }
        public Nullable<long> status5 { get; set; }
        public Nullable<long> status6 { get; set; }
        public string BranchCode { get; set; }
        public string saccocode { get; set; }
    }
}
