//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Price
    {
        public long Id { get; set; }
        public string SaccoCode { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Products { get; set; }
        public Nullable<decimal> SubsidyQty { get; set; }
        public Nullable<decimal> SubsidyPrice { get; set; }
        public string DrAccNo { get; set; }
        public string CrAccNo { get; set; }
        public string TransportDrAccNo { get; set; }
        public string TransportCrAccNo { get; set; }
    }
}
