//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Receipts
    {
        public long ID { get; set; }
        public string RNo { get; set; }
        public string Vendor { get; set; }
        public string DelNo { get; set; }
        public Nullable<double> Qnty { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Remarks { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
    }
}
