//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Requisition
    {
        public long id { get; set; }
        public string RNo { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string CostCentre { get; set; }
        public Nullable<bool> ServiceReq { get; set; }
        public string IName { get; set; }
        public string Make { get; set; }
        public Nullable<double> Qnty { get; set; }
        public string Description { get; set; }
        public string AuditId { get; set; }
        public Nullable<System.DateTime> AuditDatetime { get; set; }
        public string Rbatch { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> pricing { get; set; }
    }
}
