//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_sconribution
    {
        public long id { get; set; }
        public Nullable<long> sno { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public decimal amount { get; set; }
        public decimal bal { get; set; }
        public string transdescription { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdate { get; set; }
        public string mno { get; set; }
        public long toledgers { get; set; }
        public System.DateTime datepostedtoledger { get; set; }
        public string userledger { get; set; }
        public string Remarks { get; set; }
    }
}
