//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Shares
    {
        public long id { get; set; }
        public string sno { get; set; }
        public Nullable<decimal> bal { get; set; }
        public string IdNo { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Loc { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string pmode { get; set; }
        public Nullable<bool> Cash { get; set; }
        public string Period { get; set; }
        public Nullable<decimal> Amnt { get; set; }
        public string AuditId { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public decimal Shares { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
        public string Mno { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> PREMIUM { get; set; }
        public Nullable<decimal> spu { get; set; }
        public string SaccoCode { get; set; }
        public string zone { get; set; }
    }
}
