//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_SMSCompany
    {
        public long Id { get; set; }
        public string Phone { get; set; }
        public string Message { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
