//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_SupplierCumlative
    {
        public long Id { get; set; }
        public string SNo { get; set; }
        public string Names { get; set; }
        public Nullable<decimal> Cummulative { get; set; }
        public string AuditId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SaccoCode { get; set; }
        public string Branch { get; set; }
        public string ProductType { get; set; }
    }
}
