//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_supplier_deduc
    {
        public long Id { get; set; }
        public Nullable<long> SNo { get; set; }
        public Nullable<System.DateTime> Date_Deduc { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
        public Nullable<long> yyear { get; set; }
        public string Remarks { get; set; }
        public string Branch { get; set; }
        public Nullable<int> Bonus { get; set; }
        public int status1 { get; set; }
        public int status2 { get; set; }
        public int status3 { get; set; }
        public int status4 { get; set; }
        public int status5 { get; set; }
        public int status6 { get; set; }
        public string branchcode { get; set; }
    }
}
