//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Suppliers
    {
        public long Id { get; set; }
        public Nullable<long> LOCAL_ID { get; set; }
        public string SNo { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
        public string IdNo { get; set; }
        public string Names { get; set; }
        public string AccNo { get; set; }
        public string Bcode { get; set; }
        public string BBranch { get; set; }
        public string Type { get; set; }
        public string Village { get; set; }
        public string Location { get; set; }
        public string Division { get; set; }
        public string District { get; set; }
        public string County { get; set; }
        public Nullable<bool> Trader { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> Approval { get; set; }
        public string Branch { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string Town { get; set; }
        public string Email { get; set; }
        public string TransCode { get; set; }
        public string sign { get; set; }
        public string photo { get; set; }
        public string AuditId { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
        public string scode { get; set; }
        public bool Loan { get; set; }
        public string Compare { get; set; }
        public string isfrate { get; set; }
        public string frate { get; set; }
        public string rate { get; set; }
        public Nullable<int> hast { get; set; }
        public string Br { get; set; }
        public string mno { get; set; }
        public Nullable<long> branchcode { get; set; }
        public string HasNursery { get; set; }
        public Nullable<long> Notrees { get; set; }
        public string aarno { get; set; }
        public Nullable<System.DateTime> tmd { get; set; }
        public long Landsize { get; set; }
        public long thcpactive { get; set; }
        public long thcppremium { get; set; }
        public string status { get; set; }
        public Nullable<long> status2 { get; set; }
        public Nullable<long> status3 { get; set; }
        public Nullable<long> status4 { get; set; }
        public Nullable<long> status5 { get; set; }
        public string status6 { get; set; }
        public string types { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string freezed { get; set; }
        public string mass { get; set; }
        public Nullable<long> status1 { get; set; }
        public Nullable<long> Run { get; set; }
        public string Zone { get; set; }
    }
}
