//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_SupplyDeducTrans
    {
        public long id { get; set; }
        public Nullable<long> SNo { get; set; }
        public string DedCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string TranType { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
        public string yyear { get; set; }
        public string isfrate { get; set; }
        public Nullable<double> rate { get; set; }
    }
}
