//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_tbl_trends
    {
        public long id { get; set; }
        public long sno { get; set; }
        public Nullable<decimal> kgs { get; set; }
        public Nullable<decimal> average { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
    }
}
