//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Transport_Deduc
    {
        public long id { get; set; }
        public string TransCode { get; set; }
        public Nullable<System.DateTime> TDate_Deduc { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string auditid { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
        public Nullable<long> yyear { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> AI { get; set; }
    }
}
