//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_TransDetailed
    {
        public long id { get; set; }
        public Nullable<long> SNo { get; set; }
        public Nullable<double> QNTY { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Subsidy { get; set; }
        public string Trans_Code { get; set; }
        public Nullable<System.DateTime> EndPeriod { get; set; }
        public Nullable<int> MMonth { get; set; }
        public Nullable<int> YYear { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
    }
}
