//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_trans_frate
    {
        public long ID { get; set; }
        public string Trans_code { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<long> days { get; set; }
        public decimal Amount { get; set; }
        public string auditid { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
        public decimal Total { get; set; }
        public string isfrate { get; set; }
    }
}
