//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_VehicleTill
    {
        public long id { get; set; }
        public int Code { get; set; }
        public string Vehicle { get; set; }
        public string TillNo { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Auditdatetime { get; set; }
        public string UserID { get; set; }
        public string Dr { get; set; }
        public string Cr { get; set; }
        public Nullable<long> Run { get; set; }
    }
}
