//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        public long ID { get; set; }
        public string Dcode { get; set; }
        public string DName { get; set; }
        public System.DateTime Transdate { get; set; }
        public decimal Dispatchkgs { get; set; }
        public decimal TIntake { get; set; }
        public string auditid { get; set; }
        public string Remarks { get; set; }
        public string Branch { get; set; }
    }
}
