//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRanx
    {
        public string DCode { get; set; }
        public decimal From { get; set; }
        public decimal To { get; set; }
        public decimal rate { get; set; }
        public bool Percentage { get; set; }
        public System.DateTime Audittime { get; set; }
        public string auditid { get; set; }
    }
}
