//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRAWNSTOCK
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string QUANTITY { get; set; }
        public string TOTALAMOUNT { get; set; }
        public string PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public string USERNAME { get; set; }
        public string PRICEEACH { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
        public string BranchF { get; set; }
        public string Branch { get; set; }
        public Nullable<int> updated { get; set; }
        public string Buying { get; set; }
        public Nullable<int> AI { get; set; }
        public string commission { get; set; }
        public string saccocode { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
    }
}
