//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyMa_policies
    {
        public long ID { get; set; }
        public long passLength { get; set; }
        public long PassExpire { get; set; }
        public long enforcePassHistory { get; set; }
        public long ephnum { get; set; }
        public long minpexpire { get; set; }
        public long pcomplexity { get; set; }
        public long spreverse { get; set; }
    }
}
