//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long ID { get; set; }
        public string EmpNo { get; set; }
        public string MemberNo { get; set; }
        public string SaccoCode { get; set; }
        public string Surname { get; set; }
        public string Othernames { get; set; }
        public string IDNO { get; set; }
        public string Category { get; set; }
        public string Department { get; set; }
        public string EmpStatus { get; set; }
        public string nationality { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string maritalstatus { get; set; }
        public string RELIGION { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE { get; set; }
        public string NSSFCode { get; set; }
        public string NHIFCode { get; set; }
        public string PinNo { get; set; }
        public string eposition { get; set; }
        public string BankAccNo { get; set; }
        public string Bank { get; set; }
        public Nullable<System.DateTime> AUDITTIME { get; set; }
        public Nullable<System.DateTime> EmpDate { get; set; }
    }
}
