//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLMD
    {
        public long Id { get; set; }
        public string Sno { get; set; }
        public Nullable<int> ExoticCattle { get; set; }
        public Nullable<int> IndigenousCattle { get; set; }
        public Nullable<int> IndigenousChicken { get; set; }
        public Nullable<int> Sheep { get; set; }
        public Nullable<int> Goats { get; set; }
        public Nullable<int> Camels { get; set; }
        public Nullable<int> Donkeys { get; set; }
        public Nullable<int> Pigs { get; set; }
        public Nullable<int> BeeHives { get; set; }
        public Nullable<int> Boys { get; set; }
        public Nullable<int> Girls { get; set; }
        public Nullable<int> Deaths { get; set; }
        public Nullable<int> Disabled { get; set; }
        public Nullable<int> PostGraduates { get; set; }
        public Nullable<int> Graduates { get; set; }
        public Nullable<int> UnderGraduates { get; set; }
        public Nullable<int> Secondary { get; set; }
        public Nullable<int> Primary { get; set; }
        public Nullable<int> Nursery { get; set; }
        public string SaccoCode { get; set; }
    }
}
