//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLedger
    {
        public Nullable<System.DateTime> Transdate { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> Debits { get; set; }
        public Nullable<decimal> Credits { get; set; }
        public Nullable<decimal> AccBal { get; set; }
        public string Chequeno { get; set; }
        public string Description { get; set; }
        public string GLname { get; set; }
        public bool Recon { get; set; }
        public string Auditid { get; set; }
    }
}
