//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLSETUP
    {
        public long GLid { get; set; }
        public string GlCode { get; set; }
        public string GlAccName { get; set; }
        public string AccNo { get; set; }
        public string GlAccType { get; set; }
        public string GlAccGroup { get; set; }
        public string GlAccMainGroup { get; set; }
        public string NormalBal { get; set; }
        public string GlAccStatus { get; set; }
        public decimal OpeningBal { get; set; }
        public decimal CurrentBal { get; set; }
        public Nullable<decimal> Bal { get; set; }
        public Nullable<decimal> Curr_Code { get; set; }
        public string AuditOrg { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string Curr { get; set; }
        public Nullable<decimal> Actuals { get; set; }
        public Nullable<decimal> Budgetted { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<bool> IsSubLedger { get; set; }
        public string AccCategory { get; set; }
        public decimal NewGLOpeningBal { get; set; }
        public System.DateTime NewGLOpeningBalDate { get; set; }
        public string Branch { get; set; }
        public string Hcode { get; set; }
        public string Mcode { get; set; }
        public string Hname { get; set; }
        public string Header { get; set; }
        public string Mheader { get; set; }
        public Nullable<int> Iorder { get; set; }
        public Nullable<int> border { get; set; }
        public string type { get; set; }
        public string subtype { get; set; }
        public bool isRearning { get; set; }
        public bool Issuspense { get; set; }
        public Nullable<long> Run { get; set; }
    }
}
