//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLTRANSACTIONS2
    {
        public long ID { get; set; }
        public string Accname { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Available { get; set; }
        public string Accno { get; set; }
        public string Transdescription { get; set; }
        public string ChequeNo { get; set; }
        public string Transtype { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public string AuditID { get; set; }
        public int Cash { get; set; }
    }
}
