//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLTRANSACTION
    {
        public long ID { get; set; }
        public Nullable<long> LOCAL_ID { get; set; }
        public System.DateTime TransDate { get; set; }
        public decimal Amount { get; set; }
        public string DrAccNo { get; set; }
        public string CrAccNo { get; set; }
        public string DocumentNo { get; set; }
        public string Source { get; set; }
        public string TransDescript { get; set; }
        public System.DateTime AuditTime { get; set; }
        public string AuditID { get; set; }
        public Nullable<int> Cash { get; set; }
        public Nullable<int> doc_posted { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<bool> dregard { get; set; }
        public string TimeTrans { get; set; }
        public string Transactionno { get; set; }
        public string module { get; set; }
        public string pmode { get; set; }
        public string refid { get; set; }
        public Nullable<bool> RECON { get; set; }
        public int ReconID { get; set; }
        public Nullable<long> Run { get; set; }
    }
}
