//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchedreport
    {
        public long id { get; set; }
        public Nullable<long> EX_ID { get; set; }
        public Nullable<long> BFUB_ID { get; set; }
        public string SNO { get; set; }
        public string NAMES { get; set; }
        public Nullable<long> Withdrawn { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string Details { get; set; }
        public string NARRATION { get; set; }
        public string phoneno { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> valuedate { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
    }
}
