//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milktransfer
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public Nullable<decimal> fromStation { get; set; }
        public Nullable<decimal> Tostation { get; set; }
        public string FromBranch { get; set; }
        public string ToBranch { get; set; }
        public string auditid { get; set; }
        public Nullable<decimal> Intake { get; set; }
        public string Code { get; set; }
    }
}
