//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class milkcontrol2
    {
        public long Id { get; set; }
        public Nullable<decimal> Intake { get; set; }
        public Nullable<decimal> SQuantity { get; set; }
        public Nullable<decimal> Reject { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public string auditid { get; set; }
        public Nullable<decimal> cfa { get; set; }
        public Nullable<decimal> Spillage { get; set; }
        public Nullable<decimal> FromStation { get; set; }
        public Nullable<decimal> Tostation { get; set; }
        public Nullable<decimal> Bf { get; set; }
        public string code { get; set; }
        public string Branch { get; set; }
    }
}
