//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mpesab
    {
        public long id { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<System.DateTime> CompletionTime { get; set; }
        public Nullable<System.DateTime> InitiationTime { get; set; }
        public string Details { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<decimal> PaidIn { get; set; }
        public Nullable<decimal> Withdrawn { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string BalanceConfirmed { get; set; }
        public string ReasonType { get; set; }
        public string OtherPartyInfo { get; set; }
        public string REFERENCE { get; set; }
        public string LinkedTransactionID { get; set; }
        public string phoneno { get; set; }
        public string NARRATION { get; set; }
        public string AcNo { get; set; }
        public long RUN { get; set; }
        public Nullable<long> run2 { get; set; }
        public System.DateTime auditdatetime { get; set; }
    }
}
