//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySlip
    {
        public long Id { get; set; }
        public string EmpNo { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PDate { get; set; }
        public string AuditId { get; set; }
        public string SaccoCode { get; set; }
    }
}
