//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductIntake
    {
        public long Id { get; set; }
        public string Sno { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.TimeSpan> TransTime { get; set; }
        public string ProductType { get; set; }
        public Nullable<decimal> QSupplied { get; set; }
        public Nullable<decimal> PPU { get; set; }
        public Nullable<decimal> CR { get; set; }
        public Nullable<decimal> DR { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Description { get; set; }
        public bool Paid { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public string AuditId { get; set; }
        public Nullable<System.DateTime> auditdatetime { get; set; }
        public string Branch { get; set; }
        public string SaccoCode { get; set; }
        public string DrAccNo { get; set; }
        public string CrAccNo { get; set; }
    }
}
