//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBMP
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string canno { get; set; }
        public string TPC { get; set; }
        public string TSC { get; set; }
        public string ALC { get; set; }
        public string ANR { get; set; }
        public string Remarks { get; set; }
        public string Pscore { get; set; }
        public string Cname { get; set; }
        public System.DateTime Auditdatetime { get; set; }
    }
}
