//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Refund()
        {
            this.RefundDetails = new HashSet<RefundDetail>();
            this.RefundJournals = new HashSet<RefundJournal>();
        }
    
        public System.Guid Id { get; set; }
        public string Ref { get; set; }
        public string Vendor { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Journal { get; set; }
        public string PaymentReference { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Arrears { get; set; }
        public string Status { get; set; }
        public string ReceipientBank { get; set; }
        public string IncoTerm { get; set; }
        public string FiscalPosition { get; set; }
        public string Personnel { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SaccoCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefundDetail> RefundDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefundJournal> RefundJournals { get; set; }
    }
}
