//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sisold
    {
        public int ID { get; set; }
        public string S_no { get; set; }
        public string p_code { get; set; }
        public string supplier { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public string r_no { get; set; }
    }
}
