//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSubscription
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string Phone { get; set; }
        public string Subscription { get; set; }
        public string Freq { get; set; }
        public bool Active { get; set; }
        public string AuditId { get; set; }
        public System.DateTime AuditDateTime { get; set; }
        public string LastSent { get; set; }
    }
}
