//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sno
    {
        public long Receipthnoid { get; set; }
        public string Receiptno { get; set; }
        public System.DateTime Auditdate { get; set; }
        public string AuditId { get; set; }
    }
}
