//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public short Supplier_Number { get; set; }
        public Nullable<System.DateTime> Date_Began { get; set; }
        public string Id_Number { get; set; }
        public string First_Name { get; set; }
        public string Other_Names { get; set; }
        public string Account_Number { get; set; }
        public string Bank_Name { get; set; }
        public string Branch { get; set; }
        public string Registered_By { get; set; }
        public string Types { get; set; }
        public string Location { get; set; }
        public string Trader { get; set; }
        public string BranchSupplier { get; set; }
        public string Names { get; set; }
        public string saccocode { get; set; }
    }
}
