//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSPARAM
    {
        public Nullable<decimal> LoanInterest { get; set; }
        public Nullable<decimal> ShareInterest { get; set; }
        public Nullable<int> MinGuarantors { get; set; }
        public Nullable<int> MaxGuarantors { get; set; }
        public Nullable<decimal> LoanToShareRatio { get; set; }
        public Nullable<int> MinLoanPeriod { get; set; }
        public Nullable<decimal> MinTotShares { get; set; }
        public Nullable<int> MaxLoans { get; set; }
        public Nullable<int> MaxContribPeriod { get; set; }
        public Nullable<decimal> BankInterest { get; set; }
        public Nullable<int> MinDivPeriod { get; set; }
        public string DefFundID { get; set; }
        public Nullable<decimal> DeductAmt { get; set; }
        public string SelfGuar { get; set; }
        public Nullable<decimal> GuarShareRatio { get; set; }
        public string CompanyName { get; set; }
        public string AuditID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public Nullable<int> ShareMaturity { get; set; }
        public Nullable<int> withdrawalnotice { get; set; }
        public Nullable<decimal> InsPremium { get; set; }
        public Nullable<decimal> ShareCapital { get; set; }
        public Nullable<double> Depositinterest { get; set; }
        public Nullable<decimal> RegFees { get; set; }
        public Nullable<decimal> ByLaws { get; set; }
        public Nullable<decimal> Loandefaulted { get; set; }
        public Nullable<decimal> DormancyPeriod { get; set; }
        public short LoanRecoveryOption { get; set; }
    }
}
