//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TFSCOSTCENTRES
    {
        public int CSTCTRID { get; set; }
        public string CSTCTRNAME { get; set; }
        public string CSTCTRDESCRIPTION { get; set; }
        public string DEXCH_TTYPE { get; set; }
        public string DEXCH_ORGCODE { get; set; }
        public string C__SYNCHRO { get; set; }
        public string FACTCODE_FK { get; set; }
    }
}
