//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempGlTransaction
    {
        public System.DateTime Transdate { get; set; }
        public string Transtype { get; set; }
        public decimal Amount { get; set; }
        public string Chequeno { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<bool> Recon { get; set; }
        public string AccNo { get; set; }
        public string TransDescript { get; set; }
    }
}
