//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporter
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> RateCom { get; set; }
        public string Bank_Name { get; set; }
        public string Acc_Number { get; set; }
        public string Branch { get; set; }
        public string BranchTransporter { get; set; }
        public string isfrate { get; set; }
        public Nullable<int> frate { get; set; }
        public Nullable<double> rate { get; set; }
    }
}
