//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string TransactionNo { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransDate { get; set; }
        public string AuditId { get; set; }
        public System.DateTime AuditTime { get; set; }
        public string transDescription { get; set; }
        public string Status { get; set; }
    }
}
