//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccounts1
    {
        public string UserName { get; set; }
        public string UserLoginID { get; set; }
        public string Password { get; set; }
        public string UserGroup { get; set; }
        public string PassExpire { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> SUPERUSER { get; set; }
        public string AssignGl { get; set; }
        public string DepCode { get; set; }
        public string levels { get; set; }
        public Nullable<bool> Authorize { get; set; }
        public string Status { get; set; }
        public string Department { get; set; }
        public string sign { get; set; }
        public string expirydate { get; set; }
        public string userstatus { get; set; }
        public string passwordStatus { get; set; }
        public string euser { get; set; }
        public Nullable<long> vendor_ID { get; set; }
        public Nullable<long> count { get; set; }
        public string Email { get; set; }
        public string branchcode { get; set; }
        public string Branch { get; set; }
    }
}
