//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBanking_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vender
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PhoneNo { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string SalesPerson { get; set; }
        public string PurchasePaymentTerms { get; set; }
        public string SalesPaymentTerms { get; set; }
        public string FiscalPosition { get; set; }
        public string Ref { get; set; }
        public string Industry { get; set; }
        public string APGlAccount { get; set; }
        public string Bank { get; set; }
        public string BankAccount { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string Personnel { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SaccoCode { get; set; }
    }
}
